Add a workaround for a bug in rubygems that causes Travis CI to fail
Error message was:
/home/travis/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/site_ruby/1.8/rubygems/specification.rb:325:in
`sort': undefined method `<=>' for nil:NilClass (NoMethodError)